### PR TITLE
translatation: Arabic

### PR DESCRIPTION
**Pull request by vloddot**
Also removed the dummy language from languages.json, you can edit it back if you like, seems you forgot?

### CODE REVIEW

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
Missing keys `messages.inputField.sendMessageText` and `messages.inputField.permissionDeniedText`

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
The context markers in messages.inputFild* and messages.invite.memberCountText are missing
Sorry for constantly moving the goal here, but as it is, the translation will cause crashes

**Comment by vloddot** [comment]
I still need a way to mark a specific language as RTL.

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
Will do

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
Done

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
Looks good; merging

**Pull request merged**
